import { ArrowLeft, Minus, Plus, Ticket } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useState } from 'react';
import { getEvent } from '../data/events.js';
import { useBookings } from '../context/BookingContext.jsx';

export default function Booking() {
  const event = getEvent(useParams().id); const navigate = useNavigate(); const { addBooking } = useBookings(); const [selected, setSelected] = useState(event?.tickets[0]?.id); const [quantity, setQuantity] = useState(1); const [form, setForm] = useState({ name: '', email: '', phone: '' }); const [errors, setErrors] = useState({});
  const ticket = event?.tickets.find((item) => item.id === selected); const subtotal = (ticket?.price || 0) * quantity; const fee = Math.max(5, Math.round(subtotal * 0.05)); const total = subtotal + fee;
  if (!event) return <div className="page-shell container-eventra empty-state"><h1>404</h1><Link className="button button-gold" to="/events">Back to events</Link></div>;
  const validate = () => { const next = {}; if (!form.name.trim()) next.name = 'Name is required.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = 'Enter a valid email address.'; if (!/^\+?[0-9 ()-]{7,20}$/.test(form.phone)) next.phone = 'Enter a valid phone number.'; setErrors(next); return Object.keys(next).length === 0; };
  const confirm = (e) => { e.preventDefault(); if (!validate()) return; const random = typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID().slice(0, 5).toUpperCase() : `${Date.now()}`.slice(-5); const booking = { id: `EVT-${random}`, eventId: event.id, eventTitle: event.title, eventDate: event.date, image: event.image, user: form, tickets: [{ type: ticket.name, quantity, price: ticket.price }], subtotal, serviceFee: fee, total, status: 'confirmed', createdAt: new Date().toISOString() }; addBooking(booking); navigate('/booking-success', { state: { booking } }); };
  return <div className="page-shell container-eventra booking-page"><Link className="back-link" to={`/events/${event.id}`}><ArrowLeft size={14} /> Back to event</Link><div className="booking-layout"><form className="booking-form" onSubmit={confirm}><p className="eyebrow">Book / 01</p><h1>Choose your <em>tickets.</em></h1><div className="ticket-options">{event.tickets.map((item) => <button type="button" key={item.id} className={selected === item.id ? 'ticket-option active' : 'ticket-option'} onClick={() => setSelected(item.id)}><Ticket size={18} /><span><strong>{item.name}</strong><small>{item.note}</small></span><b>{item.price ? `$${item.price}` : 'Free'}</b></button>)}</div><div className="quantity-row"><span>Quantity <small>Maximum 5 tickets</small></span><div><button type="button" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={15} /></button><b>{quantity}</b><button type="button" onClick={() => setQuantity(Math.min(5, quantity + 1))}><Plus size={15} /></button></div></div><p className="eyebrow form-eyebrow">02 — Your information</p><div className="form-grid">{[['name', 'Full name', 'text'], ['email', 'Email address', 'email'], ['phone', 'Phone number', 'tel']].map(([key, label, type]) => <label key={key}>{label}<input required type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />{errors[key] && <small className="field-error">{errors[key]}</small>}</label>)}</div><button className="button button-gold confirm-button">Confirm booking <ArrowLeft size={15} /></button></form><aside className="booking-summary"><p className="eyebrow">Your booking</p><h2>{event.title}</h2><p>{ticket.name} × {quantity}</p><div><span>Subtotal</span><b>${subtotal}</b><span>Service fee</span><b>${fee}</b></div><hr /><strong>Total <em>${total}</em></strong></aside></div></div>;
}
