import { ArrowLeft, ArrowUpRight, CalendarDays, Clock3, ExternalLink, Mail, MapPin } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getEvent } from '../data/events.js';
import Countdown from '../events/Countdown.jsx';

export default function EventDetails() {
  const event = getEvent(useParams().id);
  if (!event) return <div className="page-shell container-eventra empty-state"><h1>404</h1><p>This experience doesn't exist.</p><Link className="button button-gold" to="/events">Explore events</Link></div>;
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${event.location.venue}, ${event.location.city}`)}`;
  return <div className="detail-page"><div className="detail-hero container-eventra"><div className="detail-image" style={{ backgroundImage: `url(${event.image})` }} /><div className="detail-copy"><Link className="back-link" to="/events"><ArrowLeft size={14} /> Back to explore</Link><p className="eyebrow">{event.category} · {event.type}</p><h1>{event.title}</h1><p className="detail-description">{event.description}</p><div className="detail-meta"><span><CalendarDays size={17} /> {event.date}</span><span><Clock3 size={17} /> {event.time}</span><span><MapPin size={17} /> {event.location.venue}, {event.location.city}</span></div><Countdown date={event.date} time={event.time} /><Link className="button button-gold" to={`/book/${event.id}`}>Book tickets <ArrowUpRight size={16} /></Link></div></div><div className="detail-sections container-eventra"><section><p className="eyebrow">01 — About</p><h2>Make the moment <em>count.</em></h2><p>{event.description} Expect meaningful encounters, considered details, and an atmosphere designed to stay with you.</p></section><section><p className="eyebrow">02 — Schedule</p><div className="schedule">{event.schedule.map(([time, title]) => <div key={time}><strong>{time}</strong><span>{title}</span></div>)}</div></section><section><p className="eyebrow">03 — Organizer</p><h3>{event.organizer.name}</h3><p>{event.organizer.detail}</p><a className="text-link" href={`mailto:${event.organizer.email}`}><Mail size={14} /> {event.organizer.email}</a>{event.organizer.website && <a className="text-link" href={event.organizer.website} target="_blank" rel="noreferrer"><ExternalLink size={14} /> Website</a>}</section><section className="venue-section"><p className="eyebrow">04 — Venue</p><h3>{event.location.venue}</h3><p>{event.location.city}</p><a className="button button-outline" href={mapUrl} target="_blank" rel="noreferrer">View location <MapPin size={15} /></a></section></div></div>;
}
